### ISSUE TITLE
80k? at least 600k

### ISSUE THREAD

**Issue by albandaft** [OasisDigital/angular-aot-es2015-rollup#1]
Hi there 
I downloaded and test this app on local. The size on wire in my case result of almost 600kb 350kb of bundle? How did you got that result?
<img width="708" alt="screen shot 2017-03-29 at 22 34 36" src="https://cloud.githubusercontent.com/assets/22888509/24477740/176e80ea-14d0-11e7-93f7-3cd6bd168ffb.png">

**Comment by kylecordes** [comment]
The size I am looking at it only the JS size, which as you point out is 349KB in this screen shot. To see the actual on-the-wire size with compression, there are two options:

1. Set up your files to be served by a web server with GZip or Brotli compression.
2. Ignore the size of the bundle.js file itself, and run GZip or Brotli compression on it - then look at the file size compressed. This will be the size "on the wire" if you were to deploy in production with HTTP compression.

I did 2 - you can see the results (assuming you ran the build script) by looking at the `bundle.js.br` file.

As far as I can tell, most people look at and care about 2, the compressed size, rather than the uncompressed size.

**Comment by albandaft** [comment]
@kylecordes Cool. Thank you!!
